language: node_js
node_js:
  - 10.16.0
addons:
  ssh_known_hosts:
    - nams.site
    - 13.112.54.35
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_ac50f86d9e3d_key -iv $encrypted_ac50f86d9e3d_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
install:
  - yarn
  - yarn build:ssr
script: true
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - scp -r -o StrictHostKeyChecking=no dist/ ubuntu@13.112.54.35:/usr/app/phot
  - ssh ubuntu@13.112.54.35 -o StrictHostKeyChecking=no 'pm2 restart web'
