language: node_js
node_js:
  - 10.16.0
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_ac50f86d9e3d_key -iv $encrypted_ac50f86d9e3d_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
install:
  - yarn
  - yarn build:ssr
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - scp -r -o StrictHostKeyChecking=no dist/ ubuntu@13.112.54.35:/usr/app/phot/dist
  - ssh ubuntu@13.112.54.35 -o StrictHostKeyChecking=no 'cd ~/usr/app/phot/dist && git pull
    && yarn && yarn build:ssr'
script: true
